apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsapi
  template:
    metadata:
      labels:
        app: devopsapi
    spec:
      containers:
        - name: Deploy to Kubernetes
          run: |
            kubectl set image deployment/devopsapi devopsapi=${{ secrets.DOCKER_USERNAME }}/devopsapi-e2e:${{ github.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
